### PR TITLE
Implemented Light Theme

### PR DESCRIPTION
**Pull request by msalmeron**
### What does this PR fix/introduce?
Light Theme switch and styles implemented.

### Reviewers
@andrzej-casper @Adrian-Wrona

### CODE REVIEW

**Comment by melpadden** [comment]
@msalmeron please fix broken external links (see build failure)

**Comment by msalmeron** [comment]
> @msalmeron please fix broken external links (see build failure)

@melpadden the broken link is coming from [this commit](https://github.com/casper-network/docs-new/commit/c7bb9048e10577ff660deaa8cf082b1d05b5bcd2) not related to any of our changes. This may be related to this change not being in the doc production site yet, but not sure about this.

Let me know if any actions from our side are needed in order to merge this PR

Thanks!

**Comment by melpadden** [comment]
@msalmeron I'l look into this, should never happen. You may need to do a rebase at some point once the underlying is fixed

**Review by ghost — CHANGES_REQUESTED** [review]
image

:ok_hand: I quickly went through the code, and everything seems to be okay. I also tested it visually and found couple UI bugs, but nothing related to theme mode.

:exclamation: Please fix failing build by merging the latest `dev-new`, then we can merge this PR.

**Review by ghost — APPROVED** [review]
Let's ship it!

**Pull request merged**
