### PR TITLE
40 template frontend stack react

### PR DESCRIPTION
**Pull request by dylanireland**
### What does this PR fix/introduce?
Adds Building-dApps/TemplateFrontendStackReact

### Additional context
Shows examples of common functionalities implemented with React

### Checklist

- [x] I ran the docs locally using `yarn install` and `yarn run start`.
- [x] My changes follow the [Casper docs style guidelines](https://docs.casperlabs.io/workflow/contribute/).
- [x] All links (internal and external) have been verified.
- [x] All technical procedures have been tested (if you want help with this, mention it in [Reviewers](#reviewers)).

### Reviewers
@melpadden 
@KMCreatesWorlds 
@andrzej-casper

### CODE REVIEW

**Comment by Adrian-Wrona** [comment]
@KMCreatesWorlds to check if this is in line with best practises

**Comment by ghost** [comment]
@dylanireland [CI/CD is failing](https://github.com/casper-network/docs-new/actions/runs/4300335740/jobs/7496438565) because of invalid external links:
```
━ FAIL ━ ./source/docs/casper/developers/dapps/template-frontend.md
   ━ Not Found (404): https://docs.casperlabs.io/glossary/A/#account-hash
```

**Note:** You can reproduce this fail locally with `yarn check:externals`.

In this case, those glossary references should be **internal**, and we prefer to use relative file references (with .md extension). So `https://docs.casperlabs.io/glossary/A/#account-hash` should be replaced with `../../concepts/glossary/A.md#account-hash`. I allowed myself to fix this in https://github.com/casper-network/docs-new/pull/146/commits/121d2b095ff7cce271555b8845211e0c7f33ac4b.

**Comment by ghost** [comment]
Now CI/CD finished successfully :tada:, so it is ready to be reviewed by @KMCreatesWorlds.

**Review by KMCreatesWorlds — CHANGES_REQUESTED** [review]
it's a good beginning of a chapter. 
I think what is important here is the proper structuring of the frontend application with all the subfolders like service and API layer. 
Our goal here is to give best practices for the developers so they can quickly start prototyping an app. Lets discuss the structure and expand this section.
Part with the Signer is ok. That case is a common piece for all the dapps from the web. 
It might be a little more work but I think it will be worth it.

**Comment by Adrian-Wrona** [comment]
@dylanireland change the structure of both front-end and back-end, add react best practises and use functional components

**Pull request closed without merging**
