### PR TITLE
40 template frontend stack in react

### LINKED ISSUE #40: Build dApps/Template frontend stack in React
.

### PR DESCRIPTION
**Pull request by dylanireland**
### What does this PR fix/introduce?
Adds Build-dApps/template-frontend.md

### Additional context
Created new file that describes how to build a basic dApp / perform basic dApp functions using React and the Casper JS SDK.

### Checklist
(Delete any that aren't relevant)

- [x] Docs are successfully building - `yarn install && yarn run build`.
- [x] For new **internal** links I used *relative file paths* (with .md extension) - e.g. `../../faq/faq-general.md` - instead of introducing *absolute file path*, or *relative/absolute URL*.
- [x] All external links have been verified with `yarn run check:externals`.
- [x] All technical procedures have been tested (if you want help with this, mention it in [Reviewers](#reviewers)).

### Reviewers
@KMCreatesWorlds

### CODE REVIEW

**Comment by dylanireland** [comment]
CI/CD is failing because *source/docs/casper/developers/cli/installing-contracts.md* points to *https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/test/lib/Keys.test.ts* which 404s.

This is under *cli/* and not part of this PR.

**Comment by Adrian-Wrona** [comment]
@andrzej-casper please investigate

**Comment by Adrian-Wrona** [comment]
@KMCreatesWorlds and @dylanireland sync offline about this

**Comment by ghost** [comment]
CI/CD was failing on broken external link, which was fixed in https://github.com/casper-network/docs-new/pull/184. I merged the latest `dev-new`, so now it should be passing.

**Review by KMCreatesWorlds — APPROVED** [review]
The Front-end is described in a very approachable way. I think that it is a good base for the reader to then further refine the template for his/her purpose.

**Comment by andrzej-casper** [comment]
I am giving approval, just to allow merge after Karol's review :rocket:  - he is great member of Tiger team, but since he does not belong to [Casper Association organization on GitHub](https://github.com/orgs/casper-network/teams) yet, we cannot add him directly to [tiger-team](https://github.com/orgs/casper-network/teams/tiger-team/members) (code owner here).

**Review by ghost — APPROVED** [review]
I am giving approval, just to allow merge after Karol's review :rocket:  - he is great member of Tiger team, but since he does not belong to [Casper Association organization on GitHub](https://github.com/orgs/casper-network/teams) yet, we cannot add him directly to [tiger-team](https://github.com/orgs/casper-network/teams/tiger-team/members) (code owner here).

**Pull request merged**
