### PR TITLE
39 building dapps prerequisites

### LINKED ISSUE #39: Build dApps/Pre-requisites
.

### PR DESCRIPTION
**Pull request by dylanireland**
### What does this PR fix/introduce?
This PR adds Building-dApps/prerequisites
Issue #39

### Checklist

- [x] I ran the docs locally using `yarn install` and `yarn run start`.
- [x] My changes follow the [Casper docs style guidelines](https://docs.casperlabs.io/workflow/contribute/).
- [x] All links (internal and external) have been verified.

### Reviewers
@caspermel 
@KMCreatesWorlds 
@andrzej-casper

### CODE REVIEW

**Review by KMCreatesWorlds — CHANGES_REQUESTED** [review]
Generally a good outline. I would suggest adding a little more links to the ideas and maybe tutorials. 
In Point 1 for example we can say that for casper the preferred stack is the javascript sdk but you can find others and then a link to the appropriate source.
For Point 2 and 3 similar. I think it is generally better to point the reader into the right direction.
If you mention security then lets link the part were we discuss the security etc.

**Comment by ghost** [comment]
I resolved conflicts.

**Comment by dylanireland** [comment]
> Generally a good outline. I would suggest adding a little more links to the ideas and maybe tutorials. In Point 1 for example we can say that for casper the preferred stack is the javascript sdk but you can find others and then a link to the appropriate source. For Point 2 and 3 similar. I think it is generally better to point the reader into the right direction. If you mention security then lets link the part were we discuss the security etc.

I added links in sections 1 and 3 and updated the link in section 2. @KMCreatesWorlds Can you validate that this is what you are looking for? Also expanded on the security section and gave it the name "Development Considerations". @KMCreatesWorlds You mention linking to the part where we discuss security; could you add this in where you see appropriate? Thanks

**Review by KMCreatesWorlds — APPROVED** [review]
It is much better, appropriate sources are linked and the security considerations are concise and well described. The PR is therefore approved.

**Comment by Adrian-Wrona** [comment]
@dylanireland to fix the link here

**Comment by ghost** [comment]
Since this PR is depending on page from https://github.com/casper-network/docs-new/pull/171, I added empty one to make it working.

**Review by Adrian-Wrona — APPROVED** [review]

**Pull request merged**
